### ISSUE TITLE
Request for Assistance: Adding Detailed Task Descriptions to Repository

### ISSUE THREAD

**Issue by pmutua** [mikrl/django-llm-sample#1]
Hi @mikrl , I saw that you have a couple of todos you need to get done on this repository. I would be happy to assist. It would be nice if you added the issues on what needs to be done so I could help.

**Comment by pmutua** [comment]
Not supposed to be added here

**Comment by mikrl** [comment]
Hi @pmutua!

Sorry for the delay, I was traveling.

I appreciate your offer and I'll look into that and tag you on them.

Thanks for reaching out!

**Comment by pmutua** [comment]
> Hi @pmutua!
> 
> Sorry for the delay, I was traveling.
> 
> I appreciate your offer and I'll look into that and tag you on them.
> 
> Thanks for reaching out!

@mikrl great 👍🏻, let me know as soon as you get started. Have a good weekend.
